import java.io.File;
import java.io.FileWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class PDFExportService {

    public static boolean exportMatchReport(String sketchName, String matchedRecord,
                                           double similarity, double confidence,
                                           String status, String outputPath) {
        try {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
            LocalDateTime now = LocalDateTime.now();

            StringBuilder report = new StringBuilder();
            report.append("===========================================\n");
            report.append("        OCULUS MATCH REPORT\n");
            report.append("     FORENSIC SKETCH SYSTEM\n");
            report.append("===========================================\n\n");

            report.append("REPORT DATE: ").append(now.format(formatter)).append("\n\n");

            report.append("SKETCH INFORMATION:\n");
            report.append("  Sketch Name: ").append(sketchName).append("\n");
            report.append("  Analysis Date: ").append(now.format(formatter)).append("\n\n");

            report.append("MATCH RESULTS:\n");
            report.append("  Status: ").append(status).append("\n");
            if (matchedRecord != null && !matchedRecord.equals("—")) {
                report.append("  Matched Record: ").append(matchedRecord).append("\n");
                report.append("  Similarity Score: ").append(String.format("%.2f%%", similarity * 100)).append("\n");
                report.append("  Confidence Level: ").append(String.format("%.2f%%", confidence * 100)).append("\n");
            }

            report.append("\n===========================================\n");
            report.append("Generated by OCULUS Forensic System\n");
            report.append("Confidential - For authorized use only\n");

            // Write to file
            File file = new File(outputPath);
            try (FileWriter writer = new FileWriter(file)) {
                writer.write(report.toString());
            }

            System.out.println("Report exported to: " + outputPath);
            return true;

        } catch (Exception e) {
            System.err.println("Error exporting report: " + e.getMessage());
            return false;
        }
    }

    public static String getDefaultDownloadPath(String filename) {
        String userHome = System.getProperty("user.home");
        String downloadDir = userHome + File.separator + "Downloads";
        File dir = new File(downloadDir);
        if (!dir.exists()) {
            dir.mkdirs();
        }
        return downloadDir + File.separator + filename;
    }
}